[package]
name = "ZK_ecrecover"
type = "bin"
authors = ["romfol"]

[dependencies]
ecrecover = { git = "https://github.com/colinnielsen/ecrecover-noir", tag = "v1.0.0" }
 # changed manually the type in noir-array-helper "((56 - j * 8) as u8)" for "((56 - j * 8) as u64)"
noir_array_helpers = { path = "../../../nargo/github.com/colinnielsen/noir-array-helpers/v0.30.0" }